version: '3.1'
services:
  mysql:
    image: mysql:8
    container_name: mysql-8-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3308:3306"
    volumes:
      - /Users/mbhuvanadas/mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

